---
title: "Homework2_Bigfoot"
author: "Jenny Cribbs"
date: "2026-02-04"
output: html_document
---

```{r}
# install required packaged
if (!require("rspat")) remotes::install_github("rspatial/rspat")
library(terra)
library(geodata)
library(predicts)

# load bigfoot data
bf <- rspat::spat_data("bigfoot")
# look at dimensions
dim(bf)
# look at first few rows
head(bf)
# it's a dataframe
class(bf)

# make it a SpatVector
bfv <- vect(bf, geom=c("lon", "lat"), crs="+proj=longlat +datum=WGS84")

# basic plot (lon and lat no class)
terra::plot(bfv[,1:2], cex=0.5, col="red")
wrld <- geodata::world(path=".")
bnds <- wrld[wrld$NAME_0 %in% c("Canada", "Mexico", "United States"), ]
terra::lines(bnds)

```
```{r}
# pull in bioclimate data
wc <- geodata::worldclim_global("bio", res=10, ".")
# look at the worldclim data
plot(wc[[c(1, 12)]], nr=2)
# extract climate data for observed locations
bfc <- extract(wc, bfv[ , 1:2])
# check first three rows
head(bfc, 3)
# remove first column (ID not informative)
bfc <- bfc[ , -1]
# temperature versus rainfall
terra::plot(bfc[ ,"wc2.1_10m_bio_1"], bfc[, "wc2.1_10m_bio_12"], col="red",
        xlab="Annual mean temperature (°C)", ylab="Annual precipitation (mm)")

```
```{r}
# get the extent of all points
ext_bf <- ext(vect(bf[, 1:2])) + 1
ext_bf
```

```{r}
# construct background based on 5000 random samples of the extent
set.seed(0)
window(wc) <- ext_bf
bg <- spatSample(wc, 5000, "random", na.rm=TRUE, xy=TRUE)
head(bg)
```

```{r}
# plot the background points
plot(bg[, c("x", "y")])
```
```{r}
# compare presence to background in climate space
plot(bg[,1], bg[,12], xlab="Annual mean temperature (°C)",
          ylab="Annual precipitation (mm)", cex=.8)
points(bfc[,1], bfc[,12], col="red", cex=.6, pch="+")
legend("topleft", c("observed", "background"), col=c("red", "black"), pch=c("+", "o"), pt.cex=c(.6, .8))

```

